language: python

python:
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch
before_install:
    - sudo apt-get update -qq
    - sudo apt-get build-dep -qq python-pygame
    - sudo apt-get install -qq python-pygame
    system_site_packages: true
install:
    - pip install -r .travis_requirements.txt

# command to run tests
script:
  - pytest -v
